# application.yml 编码是 UTF-8
#####################################################################
server:
  # 该项目启动的端口号
  port: 10100
#####################################################################
# jwt 加密
jwt:
  # 盐值
  saltKey:  wyxjava
  #过期时间 7*24*60*60*1000=604800 秒
  expiration: 604800000
#####################################################################
spring:
  # 项目操作
  application:
    # 项目名，使用中划线
    name: java-login
  # redis 配置项
  redis:
    # 主机地址
    host: 106.15.238.19
    #端口
    port: 6379
  # 数据源
  datasource:
    # 数据源驱动   多个单词之间可以不用中划线，换成大写  【driver-class-name】【driverClassName】
    driver-class-name: com.mysql.jdbc.Driver
    # 数据库url      【时区】serverTimezone=Asia/Shanghai    【连接】useSSL=false&autoReconnect=true   【批量操作】allowMultiQueries=true  【字符编码】characterEncoding=UTF-8
    url: jdbc:mysql://cdb-jwd16kdk.bj.tencentcdb.com:10069/wyxjava?useSSL=false&allowMultiQueries=true&autoReconnect=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    # 数据库用户名
    username: root
    # 数据库用户密码
    password: wyxjava123
###########################################################################
mybatis:
  type-aliases-package: com.gsm.entity
  mapper-locations: classpath:com/gsm/dao/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.gsm.dao: DEBUG
#####################################################################
# Eureka 配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/
  instance:
    prefer-ip-address: true
###########################################################################
# 熔断器 配置
feign:
  hystrix:
    # 开启熔断器
    enabled: true