# application.yml 编码是 UTF-8
#####################################################################
server:
  # 该项目启动的端口号
  port: 10110
#####################################################################
spring:
  application:
    name: java-validated