# application.yml 编码是 UTF-8
#####################################################################
server:
  # 该项目启动的端口号
  port: 10109
#####################################################################
spring:
  # 项目操作
#  application:
    # 项目名，使用中划线
#    name: java-redis
  # redis 配置项
  redis:
    # 主机地址
    host: 127.0.0.1
    #端口
    port: 6379