spring:
  # 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-jwd16kdk.bj.tencentcdb.com:10069/wyxjava?useSSL=false&allowMultiQueries=true&autoReconnect=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: wyxjava123
###########################################################################
# mybatis 框架
mybatis:
  type-aliases-package: com.gsm.entity
  mapper-locations: classpath:com/gsm/dao/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
# log日志等级,mybatis打印sql
logging:
  level:
    com.gsm.dao: DEBUG