server:
  port: 10200
#####################################################################
# jwt 加密
jwt:
  # 盐值
  saltKey:  wyxjava
  #过期时间 7*24*60*60*1000=604800 秒
  expiration: 604800000
#####################################################################
spring:
  application:
    name: java-login-admin
  redis:
    host: 106.15.238.19
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-jwd16kdk.bj.tencentcdb.com:10069/wyxjava?useSSL=false&allowMultiQueries=true&autoReconnect=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: wyxjava123
###########################################################################
mybatis:
  type-aliases-package: com.gsm.entity
  mapper-locations: classpath:com/gsm/dao/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.gsm.dao: DEBUG
##########################################################################
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/
#      defaultZone: http://47.100.163.218:10000/eureka/
  instance:
    prefer-ip-address: true
