# application.yml 编码是 UTF-8
#####################################################################
server:
  # 该项目启动的端口号
  port: 10002
#####################################################################
spring:
  # 项目操作
  application:
    # 项目名，使用中划线
    name: java-base-sms
  # RabbitMQ 配置
  rabbitmq:
    # ip地址
    host: 106.15.238.19
    # 端口
    port: 5672
  # redis 配置项
  redis:
    # 主机地址
    host: 106.15.238.19
    #端口
    port: 6379
#####################################################################
# Eureka 配置
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/
#####################################################################
# 短信配置
sms:
  # 阿里云短信 AccessKeyId
  accessKeyId: LTAI4Fcbte7yXVfLtkcgU2BV
  # 阿里云短信 AccessKeySecret
  accessKeySecret: D5MbMuki8kvt5Ap3KEoCDn2EqigX66
  # 阿里云短信 SignName
  signName: 我要学Java
#####################################################################
# 注册模块
reg:
  # 短信
  sms:
    # 模板  您正在申请手机注册，验证码为：${code}！
    template: SMS_166475575
    # 过期时间，秒
    expireTime: 300
  #消息队列
  mq:
    fanout:
      name: regFanout
    queue:
      name: regQueue
#####################################################################
# 校验模块
check:
  # 短信
  sms:
    # 模板  您的验证码：${code}，您正进行身份验证，打死不告诉别人！
    template: SMS_160856798
    # 过期时间，秒
    expireTime: 300
  #消息队列
  mq:
    fanout:
      name: checkFanout
    queue:
      name: checkQueue
