# application.yml 编码是 UTF-8
#####################################################################
server:
  # 该项目启动的端口号
  port: 10001
#####################################################################
spring:
  # 项目操作
  application:
    # 项目名，使用中划线
    name: java-base-file
  # servlet 配置
  servlet:
    #上传文件配置
    multipart:
      #启用 http上传处理
      enabled: true
      #最大上传大小1G【默认1M】
      max-file-size: 1024MB
      max-request-size: 2048MB
#####################################################################
# Eureka 配置
eureka:
  # 客户端配置
  client:
    # 表示是否将当前模块注册到服务器上，因为该模块是 client，所以需要，不写默认 true
    register-with-eureka: true
    # 表示是否获取注册信息，不写默认 true
    fetch-registry: true
    # 表示 Eureka 客户端和服务端交互地址
    service-url:
      # Eureka客户端向该地址注册
      defaultZone: http://127.0.0.1:10000/eureka/
  # 允许各模块跨域访问
  instance:
    prefer-ip-address: true
#####################################################################
fdfs:
  # 读取时间
  so-timeout: 1500
  # 连接超时时间
  connect-timeout: 6000
  # tracker 服务配置地址列表
  tracker-list: 106.15.238.19:22122
  # 连接池
  pool:
    # 解决框架间连接池冲突
    jmx-enabled: false
