# application.yml 编码是 UTF-8
#####################################################################
server:
  servlet:
    context-path: /wyxjava
  # 该项目启动的端口号
  port: 18080
#####################################################################
spring:
  # 项目操作
  application:
    # 项目名，使用中划线
    name: java-zuul-manager
  # servlet 配置
  servlet:
    #上传文件配置
    multipart:
      #启用 http上传处理
      enabled: true
      #最大上传大小1G【默认1M】 -1不限制大小
      max-file-size: -1
      max-request-size: -1
#####################################################################
# jwt 加密
jwt:
  # 盐值
  saltKey:  wyxjava
  #过期时间 7*24*60*60=604800 秒
  expiration: 604800
#####################################################################
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/
  instance:
    prefer-ip-address: true
###########################################################################
# 网关配置
zuul:
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  # 路由规则
  routes:
    # 规则名【一般与服务名相同】
    # 文件服务
    java-base-file:
      path: /file/**
      serverid: java-base-file
    # 短信发送
    java-base-sms:
      path: /sms/**
      serverid: java-base-sms
    # 后台登录注册
    java-login-admin:
      path: /admin/**
      serverid: java-login-admin
    # 轮播图
    java-chart:
      path: /chart/**
      serverid: java-chart
    # 课程
    java-course:
      path: /course/**
      serverid: java-course
    # 反馈
    java-feedback:
      path: /feedback/**
      serverid: java-feedback
    # 996.icu
    java-icu:
      path: /icu/**
      serverid: java-icu
    # 笑话
    java-joke:
      path: /joke/**
      serverid: java-joke
    # 问题与答案
    java-qa:
      path: /qa/**
      serverid: java-qa
    # 码农交流
    java-talk:
      path: /talk/**
      serverid: java-talk
    # 消息推送
    java-websocket:
      path: /websocket/**
      serverid: java-websocket
# zuul 服务发现
ribbon:
  # 方法调用处理时间
  ReadTimeout: 60000
  # 连接时间
  ConnectTimeout: 60000
  # 最大自动重试次数
  maxAutoRetries: 2
  # 换实例重试次数
  MaxAutoRetriesNextServer: 2
###########################################################################
# 熔断器 配置
feign:
  hystrix:
    # 开启熔断器
    enabled: true
hystric:
  command:
    default:
      execution:
        timeout:
          enable: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
            ribbon:
              ReadTimeout: 60000
              ConnectTimeout: 60000